app = "launchakit-agent"          # must match the name you’ll create in dashboard
primary_region = "sin"            # pick nearest: sin/nrt/lax/fra

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false      # NEVER sleep
  auto_start_machines = true
  [[services.ports]]
    handlers = ["http"]
    port = 8080
